### PR TITLE
See also: wow you know so much about I/O dynamics in C

### PR DESCRIPTION
**Pull request by Sebbyastian**
It's a shame in all of these years of implying age makes you superior, you never bothered to read [the FAQs](https://c-faq.com/stdio/fflush.html)

### CODE REVIEW

**Comment by TheJoyfulProgrammer** [comment]
> It's a shame in all of these years of implying age makes you superior, you never bothered to read [the FAQs](https://c-faq.com/stdio/fflush.html)

Thank you for your contribution and the great link you provided. Here is a screenshot of the linked web page for others to see in case that site goes down at some point:

Screenshot from 2022-09-28 09-43-54

Let's break the question and answer down:

> **Q:** _My program's prompts and intermediate output don't always show up on the screen, especially when I pipe the output through another program._ 

As seen in the following screenshot of the compilation and execution of my code, output always showed up on screen, and it did so instantly when I was testing it.

Screenshot from 2022-09-28 09-20-24

> **A:** _It's best to use an explicit fflush(stdout) whenever output should definitely be visible (and especially if the text does not end with \n). [[footnote]](https://c-faq.com/stdio/noflush.html) Several mechanisms attempt to perform the fflush for you, at the ``right time,'' but they tend to apply only when stdout is an interactive terminal._

Since the demos output is always visible, there is no need to use the FFLUSH() function statement.

The answer mentioned, "_(and especially if the text does not end with \n)_", which is interesting, but it does not apply to my code since I use the '\n' escape sequence a few times in it.

This comment in the answer, "_Several mechanisms attempt to perform the fflush for you, at the ``right time,'_" is interesting, and I wonder if one of those "right times" is when the '\n' escape sequence is used. I think I will look through GCC's source code to see if they flush the output when it encounters the '\n' escape sequence.

The final part of the footnote in the answer, "_but they tend to apply only when stdout is an interactive terminal._" is saying that the "_...right time..._" is applied in my code since it outputs straight to the "interactive" terminal.

Overall, the modifications you suggested simply bloats the source with unneeded code, so, I will not be pushing your changes into the project.

Thank you for your time and efforts in this matter.

**Comment by Sebbyastian** [comment]
Perhaps on your computer, this code works coincidentally, whereas you can
see from the FAQ that this is a common problem with other
implementations... A common problem that you're happy to brush aside, which
makes your code non-portable (and shitty), thus not even C.

It's a shame you chose "Joyful" as an adjective, rather than "stubborn" or
"arrogant", because it seems like the latter fits you better... That or
senile.

How are you gonna play a victim after you judged credibility based on years
of experience? Because what you've demonstrated is that one can learn in a
single year what it took you many years of ignorance, and what will take
you many more years of forgetting the nonsense to correct.

It's a good thing you don't write commercial C code.

**Comment by TheJoyfulProgrammer** [comment]
> Perhaps on your computer, this code works coincidentally,

It works on every computer I have tested it on: PC, Laptop, Raspberry Pi 400. It works in many different operating systems as well:  Windows 7, 8 , 9, 10, 11, Linux Ubuntu, Linux Mint, RaspberryOS. The code even compiled and executed perfectly with the GCC compiler toolchain, TDM-GCC, MingW, Clang, and Microsoft Visual Studio C++ (also known as Visual C++).

> whereas you can see from the FAQ...

That FAQ is was written by Steve Summit, in his book "C Programming FAQs", which was published in 1995. The information he provides in his book, now on his site, is not authoritative, nor is it accurate for modern C.

> ...that this is a common problem with other implementations...

The word you used, "*implementations*", is a very broad word itself, but has no meaning to the C, or C++ programming languages.

In Steve's first book, published 1995, he was using ANSI C (or commonly called: C90). When he revised his book in 2005, he started using C99, skipping over C95 all together.

A couple years after his revised book, the new C committee started working on another revision of C, but didn't finally publish the new C specifications until 2011, which made that version be called, C11. There were numerous additions and changes made to C11, when compared to C99. This new version of C made some of the comments in Steve's latest book, inaccurate.

The code you are referring to does compile and execute accurately in C99 and above, however, that code was written in 2018, almost five years ago. Now-a-days, I only code for C17 and above (The C23 specification will be released sometime next year), which is way different the C specification that Steve used when he was writing his book.

So, I have no idea what "implementations" of C you are talking about, but, if you found an implementation that my code does not work accurately in, the please provide the name of the compiler toolchain, the version of C you are compiling for, and the operating system you are compiling on.

> A common problem that you're happy to brush aside, which makes your code non-portable (and ......).

If the C-specification is before C11, then YES! I am happy to brush it to the side, just like I brush all versions of C++ before C++17 aside. A couple of years ago, I decided to code for the latest versions of C and C++ only.

As far as code portability... Well... I already mentioned what kind of machines I code, compile, and run executables for, what operating systems I've tested the code on, and which types of processors I did these tests on, so, I have no idea what my code IS NOT PORTABLE with. Please help me understand where there is a code portability issue with my code.

> , thus not even C.

If your idea of what real C is, is C89, C90, C95, and C99, then I would suggest trying not to compare my modern C code to those older, now defunct versons.

**THE REST OF YOUR COMMENTS ARE CONSIDERED CYBER-TROLLING AND CYBER-BULLYING!!!**

***PLEASE REFRAIN YOURSELF FROM MAKING THESE TYPES OF STATEMENTS, OR ACTION WILL BE TAKEN AGAINST YOU AND YOUR ACCOUNTS.***

Thank you for your cooperation!

**Comment by Sebbyastian** [comment]
Playing the victim, I see, just as I predicted... You sociopath types are
so easy to read. First you trigger someone by making an outrageous and
uncalled for claim about their experience, then you start threatening
because you can't cope when others put the heat back on you... 😂 Then you
try to manipulate others into silencing your critics, of course!

> The only "error" to handle is if the user types anything besides the a
floating point value.

Perhaps you can explain the infinite loop that my testing environment
(which I already provided, and uses gcc and clang on Linux, btw) produces
from your code. The solution is apparently simple, but you want your
program to effectively crash on some computers (like on ideone) instead.
Fair enough! Bask in the shitty code! I don't care. Why would I care if you
want your code to suck? You could've just said, "It's a feature, not a
bug!", then maybe you'd be funny.

Also note that it isn't cyberbullying to say your code sucks. I could
instead say you're acting like an idiot, and that might be cyberbullying,
if I don't give evidence... Well, are you ready for more evidence?

If you bothered to learn about the console like the rest of us, you'd
realise the user can pipe input from a file or close stdin using
(typically) CTRL+d in Linux or CTRL+z in Windows. This is common enough
knowledge that I've had the same lecture from my highest esteemed peers,
and I respect them for it. Not all of us are haughty, humourless grumps who
only value our own experiences, groom our online persona to hide behind a
mask of apparent perfection and play the victim when what we dish is served
back to us.

> There's no need to check for EOF since the demo isn't accessing files.

Again, the testcase I linked to (hosted on ideone) proves otherwise; you
can see that the output (automatically generated) indicates that your
program has fallen into an infinite loop when no input was given.
Effectively, your code (unaltered) hangs on some systems.

What is the type of stdin? You claim that "the demo isn't accessing files",
yet the type of stdin says otherwise. You can find the type of stdin in
POSIX manpages OR the C standard. Both are acceptable in my mind.

> I read the C/C++ specifications, the C/C++ committee's websites, and all
authoritative content they write.

Now you're lying to me, clutching at straws to try to save face. I don't
believe you, as rather than opting to read the manuals (of which the C spec
is a part of) you told me earlier you were going to reverse engineer gcc to
see how newline characters are treated (😂 wrong project, you probably
meant glibc, but that's your lack of experience and guesswork talking). See:

> I think I will look through GCC's source code to see if they flush the
output when it encounters the '\n' escape sequence.

You don't need to do that if you've read the ISO standards, because of
section 7.21.3p3 (which is authoritative, unlike gcc source code):

> ... When a stream is line buffered, characters are intended to be
transmitted to or from the host environment as a block when a new-line
character is encountered.

... and then p7:

> ... the standard input and standard output streams are fully buffered if
and only if the stream can be determined not to refer to an interactive
device.

Which raises the question, since you asserted that `stdin` is not a file...
What constitutes an "interactive device" Ultimately, there is no mention of
a keyboard in the C or C++ standards. So either I believe you read the C
standard and intentionally disregard the lack of evidence for your beliefs,
whilst also ignoring the idioms they use... Or you're a liar! From what I
see, you're willing to judge my experience disrespectfully, so I'ma call
you out as a liar.

Speaking of idioms from the ISO C standards which you ignore whilst
claiming to be an expert and judging people who are probably more
knowledgeable than you, you seem to have missed [this example in
7.21.6.2p19](https://port70.net/~nsz/c/c11/n1570.html#7.21.6.2p19), in
which you can see clearly that the standard idiom is indeed to check to see
if stdin reaches EOF or any errors are triggered:

>          #include <stdio.h>
>          /* ... */
>          int count; float quant; char units[21], item[21];
>          do {
>                  count = fscanf(stdin, "%f%20s of %20s", &quant, units,
item);
>                  fscanf(stdin,"%*[^\n]");
>          } while (!feof(stdin) && !ferror(stdin));

Why would the C standard check for EOF upon stdin?

Don't bullshit me, old man; I can see through your mask. As far as your
cyberbullying/victim playing act goes, the truth is an ultimate defence to
any criminal defamation case. If you don't wanna be treated like a fool,
then stop acting like one. If you wanna press charges against me, I'll
press charges for malicious taught.

At that, I'm done proving myself to you, and I think I'm also done proving
you to you. Our correspondence is most likely done now. I have more
important things to do than waste time on an old fart who wants to act like
a baby.

**Pull request closed without merging**
